baseURL: 'https://hadesenterprisesinc.com'
title: 'Hades Enterprises'
languageCode: en-us
DefaultContentLanguage: en
enableEmoji: true
enableGitInfo: true
enableRobotsTXT: true
canonifyURLs: true
paginate: 9
enableInlineShortcodes: true

params:
  author:
  og_image: /images/defaults/featured_image.jpg
  moto: "Hades Enterprises"
  description: "We believe customer experiences are enriched when you integrate data-driven models."
  cta:
    text: We're Open Source!
    url: https://github.com/thanatos-hadesenterprisesinc

markup:
  goldmark:
    renderer:
      unsafe: true

module:
  hugoVersion:
    extended: true
    min: "0.110.0"
